import type { YieldFarmingOpportunity, UserFarm, PortfolioAllocation, HistoricalApyData } from "./types"

export const yieldFarmingOpportunities: YieldFarmingOpportunity[] = [
  {
    id: 1,
    protocol: "Aave",
    asset: "ETH-USDC",
    apy: 12.5,
    tvl: 245000000,
    risk: "Low",
    rewards: ["AAVE"],
    chain: "Ethereum",
    logo: "/placeholder.svg?height=32&width=32",
    verified: true,
    impermanentLoss: "Low",
    farmType: "Lending",
    depositFee: 0,
    withdrawFee: 0,
    harvestLockup: "None",
    lastHarvest: "2 hours ago",
  },
  {
    id: 2,
    protocol: "Curve",
    asset: "USDC-USDT-DAI",
    apy: 8.2,
    tvl: 520000000,
    risk: "Low",
    rewards: ["CRV", "CVX"],
    chain: "Ethereum",
    logo: "/placeholder.svg?height=32&width=32",
    verified: true,
    impermanentLoss: "Very Low",
    farmType: "Stablecoin LP",
    depositFee: 0,
    withdrawFee: 0,
    harvestLockup: "None",
    lastHarvest: "5 hours ago",
  },
  {
    id: 3,
    protocol: "Uniswap",
    asset: "ETH-BTC",
    apy: 18.7,
    tvl: 180000000,
    risk: "Medium",
    rewards: ["UNI"],
    chain: "Ethereum",
    logo: "/placeholder.svg?height=32&width=32",
    verified: true,
    impermanentLoss: "Medium",
    farmType: "LP",
    depositFee: 0,
    withdrawFee: 0,
    harvestLockup: "None",
    lastHarvest: "1 day ago",
  },
  {
    id: 4,
    protocol: "Compound",
    asset: "USDC",
    apy: 5.8,
    tvl: 320000000,
    risk: "Low",
    rewards: ["COMP"],
    chain: "Ethereum",
    logo: "/placeholder.svg?height=32&width=32",
    verified: true,
    impermanentLoss: "None",
    farmType: "Lending",
    depositFee: 0,
    withdrawFee: 0,
    harvestLockup: "None",
    lastHarvest: "3 hours ago",
  },
  {
    id: 5,
    protocol: "PancakeSwap",
    asset: "CAKE-BNB",
    apy: 45.2,
    tvl: 95000000,
    risk: "Medium",
    rewards: ["CAKE"],
    chain: "BSC",
    logo: "/placeholder.svg?height=32&width=32",
    verified: true,
    impermanentLoss: "Medium",
    farmType: "LP",
    depositFee: 0.1,
    withdrawFee: 0.1,
    harvestLockup: "None",
    lastHarvest: "6 hours ago",
  },
  {
    id: 6,
    protocol: "SushiSwap",
    asset: "ETH-SUSHI",
    apy: 32.4,
    tvl: 75000000,
    risk: "Medium",
    rewards: ["SUSHI"],
    chain: "Ethereum",
    logo: "/placeholder.svg?height=32&width=32",
    verified: true,
    impermanentLoss: "Medium",
    farmType: "LP",
    depositFee: 0,
    withdrawFee: 0,
    harvestLockup: "None",
    lastHarvest: "12 hours ago",
  },
  {
    id: 7,
    protocol: "Yearn Finance",
    asset: "USDC",
    apy: 9.6,
    tvl: 280000000,
    risk: "Low",
    rewards: ["YFI"],
    chain: "Ethereum",
    logo: "/placeholder.svg?height=32&width=32",
    verified: true,
    impermanentLoss: "None",
    farmType: "Vault",
    depositFee: 0.1,
    withdrawFee: 0.1,
    harvestLockup: "None",
    lastHarvest: "1 day ago",
  },
  {
    id: 8,
    protocol: "Balancer",
    asset: "ETH-DAI-USDC",
    apy: 15.3,
    tvl: 120000000,
    risk: "Medium",
    rewards: ["BAL"],
    chain: "Ethereum",
    logo: "/placeholder.svg?height=32&width=32",
    verified: true,
    impermanentLoss: "Low",
    farmType: "LP",
    depositFee: 0,
    withdrawFee: 0,
    harvestLockup: "None",
    lastHarvest: "8 hours ago",
  },
]

export const userFarms: UserFarm[] = [
  {
    id: 1,
    protocol: "Aave",
    asset: "ETH-USDC",
    deposited: 5000,
    depositValue: 5120,
    rewards: 120,
    apy: 12.5,
    timeStaked: "30 days",
    logo: "/placeholder.svg?height=32&width=32",
  },
  {
    id: 3,
    protocol: "Uniswap",
    asset: "ETH-BTC",
    deposited: 2500,
    depositValue: 2650,
    rewards: 150,
    apy: 18.7,
    timeStaked: "45 days",
    logo: "/placeholder.svg?height=32&width=32",
  },
  {
    id: 5,
    protocol: "PancakeSwap",
    asset: "CAKE-BNB",
    deposited: 1000,
    depositValue: 1120,
    rewards: 120,
    apy: 45.2,
    timeStaked: "15 days",
    logo: "/placeholder.svg?height=32&width=32",
  },
]

export const historicalApyData: HistoricalApyData[] = [
  { date: "Jan", apy: 8.2 },
  { date: "Feb", apy: 9.5 },
  { date: "Mar", apy: 12.3 },
  { date: "Apr", apy: 10.8 },
  { date: "May", apy: 11.5 },
  { date: "Jun", apy: 13.2 },
  { date: "Jul", apy: 12.5 },
  { date: "Aug", apy: 14.8 },
  { date: "Sep", apy: 15.3 },
  { date: "Oct", apy: 13.7 },
  { date: "Nov", apy: 12.9 },
  { date: "Dec", apy: 14.2 },
]

export const portfolioAllocationData: PortfolioAllocation[] = [
  { name: "Aave", value: 5120, color: "#FF6B6B" },
  { name: "Uniswap", value: 2650, color: "#4ECDC4" },
  { name: "PancakeSwap", value: 1120, color: "#FFE66D" },
]
