/**
 * Copytrading Leaderboard Generator
 *
 * Generates a Top 50 copytrading leaderboard ranked by LogGrowthPerDay
 * using wallet trading data from the last 90 days.
 *
 * See docs/features/copytrading-leaderboard.md for full methodology.
 *
 * Usage: npx tsx scripts/copytrading-leaderboard.ts
 */

import { createClient } from "@clickhouse/client";
import * as fs from "fs";
import * as path from "path";

// =============================================================================
// Configuration
// =============================================================================

const CONFIG = {
  // Simulation parameters
  betSize: 2.0, // Fixed bet size per trade ($)
  initialBankroll: 1000.0, // Starting capital ($)

  // Filter thresholds
  minTrades: 35, // Step 2: Minimum trades in 90 days
  minMarkets: 8, // Step 3: Minimum unique markets traded
  activeDays: 10, // Step 4: Must have traded within last N days
  minWalletAge: 5, // Step 5: Minimum days between first and last trade
  minWinRate: 30, // Step 6: Minimum win rate (%)
  minMedianRoi: 0.2, // Step 7: Minimum median ROI (20%)
  minMedianBetSize: 10, // Step 8: Minimum median bet size ($)

  // ROI winsorization
  roiPercentileCap: 0.95, // Cap ROI at 95th percentile

  // Output
  topN: 50, // Number of wallets to return
  outputFile: "copytrading_leaderboard_top50_v2.csv",
};

// =============================================================================
// ClickHouse Client
// =============================================================================

function getClickHouseClient() {
  return createClient({
    url: `https://${process.env.CLICKHOUSE_HOST}:${process.env.CLICKHOUSE_PORT || 8443}`,
    username: process.env.CLICKHOUSE_USER || "default",
    password: process.env.CLICKHOUSE_PASSWORD,
    database: process.env.CLICKHOUSE_DATABASE || "default",
  });
}

// =============================================================================
// Leaderboard Query
// =============================================================================

function buildLeaderboardQuery(): string {
  return `
-- Copytrading Leaderboard Query
-- Generated by scripts/copytrading-leaderboard.ts
-- See docs/features/copytrading-leaderboard.md for methodology

WITH
-- Configuration parameters
bet_size AS (SELECT ${CONFIG.betSize} AS v),
initial_bankroll AS (SELECT ${CONFIG.initialBankroll} AS v),
cutoff_90d AS (SELECT toDateTime(now() - INTERVAL 90 DAY) AS t),
cutoff_10d AS (SELECT toDateTime(now() - INTERVAL ${CONFIG.activeDays} DAY) AS t),

-- =============================================================================
-- Steps 2-8: Filter wallets based on criteria
-- =============================================================================
wallet_stats AS (
    SELECT
        wallet,
        count() AS total_trades,
        uniqExact(condition_id) AS markets_traded,
        max(entry_time) AS last_trade_time,
        min(entry_time) AS first_trade_time,
        countIf(roi > 0) AS wins,
        countIf(roi <= 0) AS losses,
        median(roi) AS median_roi_raw,
        median(cost_usd) AS median_bet_size,
        quantile(${CONFIG.roiPercentileCap})(roi) AS roi_p95,
        medianIf(roi, roi > 0) AS median_win_roi,
        medianIf(abs(roi), roi <= 0) AS median_loss_mag
    FROM pm_trade_fifo_roi_v3_mat_unified
    WHERE entry_time >= (SELECT t FROM cutoff_90d)
      AND cost_usd > 0           -- Long positions only
      AND is_closed = 1          -- Resolved trades only
      AND resolved_at IS NOT NULL
    GROUP BY wallet
    HAVING
        total_trades > ${CONFIG.minTrades}                              -- Step 2
        AND markets_traded > ${CONFIG.minMarkets}                       -- Step 3
        AND last_trade_time >= (SELECT t FROM cutoff_10d)               -- Step 4
        AND dateDiff('day', first_trade_time, last_trade_time) > ${CONFIG.minWalletAge}  -- Step 5
        AND (wins + losses) > 0
        AND wins * 100.0 / (wins + losses) > ${CONFIG.minWinRate}       -- Step 6
        AND median_roi_raw > ${CONFIG.minMedianRoi}                     -- Step 7
        AND median_bet_size > ${CONFIG.minMedianBetSize}                -- Step 8
),

-- =============================================================================
-- Step 9: Calculate winsorized ROI sum for simulation
-- =============================================================================
wallet_simulation AS (
    SELECT
        t.wallet,
        ws.total_trades,
        ws.markets_traded,
        ws.last_trade_time,
        ws.first_trade_time,
        ws.wins,
        ws.losses,
        ws.median_roi_raw,
        ws.median_bet_size,
        ws.roi_p95,
        ws.median_win_roi,
        ws.median_loss_mag,
        -- Sum of winsorized ROI (capped at p95)
        sum(least(t.roi, ws.roi_p95)) AS sum_winsorized_roi,
        -- Median of winsorized ROI
        median(least(t.roi, ws.roi_p95)) AS median_roi_winsorized
    FROM pm_trade_fifo_roi_v3_mat_unified t
    INNER JOIN wallet_stats ws ON t.wallet = ws.wallet
    WHERE t.entry_time >= (SELECT t FROM cutoff_90d)
      AND t.cost_usd > 0
      AND t.is_closed = 1
      AND t.resolved_at IS NOT NULL
    GROUP BY
        t.wallet, ws.total_trades, ws.markets_traded, ws.last_trade_time,
        ws.first_trade_time, ws.wins, ws.losses, ws.median_roi_raw,
        ws.median_bet_size, ws.roi_p95, ws.median_win_roi, ws.median_loss_mag
),

-- =============================================================================
-- Step 10: Simulation results
-- With fixed bet_size and no skipping: FinalBankroll = Initial + bet_size * sum(roi)
-- =============================================================================
final_results AS (
    SELECT
        wallet,
        total_trades,
        markets_traded,
        last_trade_time,
        first_trade_time,
        wins,
        losses,
        wins * 100.0 / (wins + losses) AS win_rate_pct,
        median_roi_winsorized,
        median_bet_size,
        median_win_roi,
        median_loss_mag,
        sum_winsorized_roi,
        -- Days active (at least 1)
        greatest(1.0, toFloat64(dateDiff('day', first_trade_time, last_trade_time))) AS days_active,
        -- Final bankroll = initial + bet_size * sum(roi)
        (SELECT v FROM initial_bankroll) + (SELECT v FROM bet_size) * sum_winsorized_roi AS final_bankroll
    FROM wallet_simulation
)

-- =============================================================================
-- Step 11-12: Rank and output leaderboard
-- =============================================================================
SELECT
    wallet AS wallet_address,

    -- LogGrowthPerDay (ranking metric)
    round(ln(final_bankroll / (SELECT v FROM initial_bankroll)) / days_active, 6) AS log_growth_per_day,

    -- Simulated return %/day
    round(((final_bankroll / (SELECT v FROM initial_bankroll)) - 1) * 100 / days_active, 4) AS sim_return_pct_per_day,

    -- ROI %/day
    round((sum_winsorized_roi / total_trades) * 100 * (total_trades / days_active), 4) AS roi_pct_per_day,

    -- Trades per day
    round(total_trades / days_active, 4) AS trades_per_day,

    -- Final bankroll
    round(final_bankroll, 2) AS final_bankroll,

    -- Trades copied (all trades, no skipping)
    total_trades AS trades_copied,

    -- Trades skipped (0 - verified with large bankroll simulation)
    0 AS trades_skipped,

    -- Edge per trade (EV)
    round((win_rate_pct / 100.0) * coalesce(median_win_roi, 0) -
          ((100 - win_rate_pct) / 100.0) * coalesce(median_loss_mag, 0), 4) AS edge_per_trade,

    -- Compounding score
    round(ln(final_bankroll / (SELECT v FROM initial_bankroll)) / days_active * (total_trades / days_active), 4) AS compounding_score,

    -- Win rate %
    round(win_rate_pct, 2) AS win_rate_pct,

    -- Median ROI % (winsorized)
    round(median_roi_winsorized * 100, 2) AS median_roi_pct_winsorized,

    -- Last trade date
    formatDateTime(last_trade_time, '%Y-%m-%d') AS last_trade_date

FROM final_results
WHERE final_bankroll > (SELECT v FROM initial_bankroll) * 0.5  -- At least 50% remaining
ORDER BY log_growth_per_day DESC
LIMIT ${CONFIG.topN}
  `.trim();
}

// =============================================================================
// Filter Funnel Query (for diagnostics)
// =============================================================================

function buildFilterFunnelQuery(): string {
  return `
-- Filter Funnel Diagnostics
WITH
cutoff_90d AS (SELECT toDateTime(now() - INTERVAL 90 DAY) AS t),
cutoff_10d AS (SELECT toDateTime(now() - INTERVAL ${CONFIG.activeDays} DAY) AS t),

base_data AS (
    SELECT
        wallet,
        count() AS total_trades,
        uniqExact(condition_id) AS markets_traded,
        max(entry_time) AS last_trade_time,
        min(entry_time) AS first_trade_time,
        countIf(roi > 0) AS wins,
        countIf(roi <= 0) AS losses,
        median(roi) AS median_roi,
        median(cost_usd) AS median_bet_size
    FROM pm_trade_fifo_roi_v3_mat_unified
    WHERE entry_time >= (SELECT t FROM cutoff_90d)
      AND cost_usd > 0 AND is_closed = 1 AND resolved_at IS NOT NULL
    GROUP BY wallet
)

SELECT
    'Step 1: 90-day window' AS step,
    count() AS wallets
FROM base_data

UNION ALL

SELECT 'Step 2: > ${CONFIG.minTrades} trades', count()
FROM base_data WHERE total_trades > ${CONFIG.minTrades}

UNION ALL

SELECT 'Step 3: > ${CONFIG.minMarkets} markets', count()
FROM base_data WHERE total_trades > ${CONFIG.minTrades} AND markets_traded > ${CONFIG.minMarkets}

UNION ALL

SELECT 'Step 4: Active in ${CONFIG.activeDays}d', count()
FROM base_data
WHERE total_trades > ${CONFIG.minTrades}
  AND markets_traded > ${CONFIG.minMarkets}
  AND last_trade_time >= (SELECT t FROM cutoff_10d)

UNION ALL

SELECT 'Step 5: > ${CONFIG.minWalletAge}d age', count()
FROM base_data
WHERE total_trades > ${CONFIG.minTrades}
  AND markets_traded > ${CONFIG.minMarkets}
  AND last_trade_time >= (SELECT t FROM cutoff_10d)
  AND dateDiff('day', first_trade_time, last_trade_time) > ${CONFIG.minWalletAge}

UNION ALL

SELECT 'Step 6: Win rate > ${CONFIG.minWinRate}%', count()
FROM base_data
WHERE total_trades > ${CONFIG.minTrades}
  AND markets_traded > ${CONFIG.minMarkets}
  AND last_trade_time >= (SELECT t FROM cutoff_10d)
  AND dateDiff('day', first_trade_time, last_trade_time) > ${CONFIG.minWalletAge}
  AND (wins + losses) > 0
  AND wins * 100.0 / (wins + losses) > ${CONFIG.minWinRate}

UNION ALL

SELECT 'Step 7: Median ROI > ${CONFIG.minMedianRoi * 100}%', count()
FROM base_data
WHERE total_trades > ${CONFIG.minTrades}
  AND markets_traded > ${CONFIG.minMarkets}
  AND last_trade_time >= (SELECT t FROM cutoff_10d)
  AND dateDiff('day', first_trade_time, last_trade_time) > ${CONFIG.minWalletAge}
  AND (wins + losses) > 0
  AND wins * 100.0 / (wins + losses) > ${CONFIG.minWinRate}
  AND median_roi > ${CONFIG.minMedianRoi}

UNION ALL

SELECT 'Step 8: Median bet > $${CONFIG.minMedianBetSize}', count()
FROM base_data
WHERE total_trades > ${CONFIG.minTrades}
  AND markets_traded > ${CONFIG.minMarkets}
  AND last_trade_time >= (SELECT t FROM cutoff_10d)
  AND dateDiff('day', first_trade_time, last_trade_time) > ${CONFIG.minWalletAge}
  AND (wins + losses) > 0
  AND wins * 100.0 / (wins + losses) > ${CONFIG.minWinRate}
  AND median_roi > ${CONFIG.minMedianRoi}
  AND median_bet_size > ${CONFIG.minMedianBetSize}

ORDER BY step
  `.trim();
}

// =============================================================================
// Main Execution
// =============================================================================

interface LeaderboardRow {
  wallet_address: string;
  log_growth_per_day: number;
  sim_return_pct_per_day: number;
  roi_pct_per_day: number;
  trades_per_day: number;
  final_bankroll: number;
  trades_copied: number;
  trades_skipped: number;
  edge_per_trade: number;
  compounding_score: number;
  win_rate_pct: number;
  median_roi_pct_winsorized: number;
  last_trade_date: string;
}

async function main() {
  console.log("=".repeat(60));
  console.log("COPYTRADING LEADERBOARD GENERATOR");
  console.log("=".repeat(60));
  console.log("\nConfiguration:");
  console.log(`  Bet Size: $${CONFIG.betSize}`);
  console.log(`  Initial Bankroll: $${CONFIG.initialBankroll}`);
  console.log(`  ROI Cap: ${CONFIG.roiPercentileCap * 100}th percentile`);
  console.log(`  Top N: ${CONFIG.topN}`);
  console.log();

  const client = getClickHouseClient();

  try {
    // Run filter funnel diagnostics
    console.log("Running filter funnel diagnostics...\n");
    const funnelResult = await client.query({
      query: buildFilterFunnelQuery(),
      format: "JSONEachRow",
    });
    const funnelData = await funnelResult.json<{ step: string; wallets: number }>();

    console.log("Filter Funnel:");
    console.log("-".repeat(50));
    for (const row of funnelData) {
      console.log(`  ${row.step}: ${row.wallets.toLocaleString()} wallets`);
    }
    console.log();

    // Run main leaderboard query
    console.log("Generating leaderboard...\n");
    const leaderboardResult = await client.query({
      query: buildLeaderboardQuery(),
      format: "JSONEachRow",
    });
    const leaderboardData = await leaderboardResult.json<LeaderboardRow>();

    // Display top 10
    console.log("Top 10 Wallets by LogGrowthPerDay:");
    console.log("-".repeat(80));
    console.log(
      "Rank | Wallet                                     | LogGrowth | Final$    | Trades"
    );
    console.log("-".repeat(80));

    for (let i = 0; i < Math.min(10, leaderboardData.length); i++) {
      const row = leaderboardData[i];
      console.log(
        `${(i + 1).toString().padStart(4)} | ${row.wallet_address} | ${row.log_growth_per_day.toFixed(4).padStart(9)} | $${row.final_bankroll.toLocaleString().padStart(8)} | ${row.trades_copied.toLocaleString()}`
      );
    }
    console.log();

    // Export to CSV
    const csvHeader = [
      "wallet_address",
      "log_growth_per_day",
      "sim_return_pct_per_day",
      "roi_pct_per_day",
      "trades_per_day",
      "final_bankroll",
      "trades_copied",
      "trades_skipped",
      "edge_per_trade",
      "compounding_score",
      "win_rate_pct",
      "median_roi_pct_winsorized",
      "last_trade_date",
    ].join(",");

    const csvRows = leaderboardData.map((row) =>
      [
        row.wallet_address,
        row.log_growth_per_day,
        row.sim_return_pct_per_day,
        row.roi_pct_per_day,
        row.trades_per_day,
        row.final_bankroll,
        row.trades_copied,
        row.trades_skipped,
        row.edge_per_trade,
        row.compounding_score,
        row.win_rate_pct,
        row.median_roi_pct_winsorized,
        row.last_trade_date,
      ].join(",")
    );

    const csvContent = [csvHeader, ...csvRows].join("\n");
    const outputPath = path.join(process.cwd(), CONFIG.outputFile);
    fs.writeFileSync(outputPath, csvContent);

    console.log(`Exported ${leaderboardData.length} wallets to ${CONFIG.outputFile}`);
    console.log("\nDone!");
  } catch (error) {
    console.error("Error:", error);
    process.exit(1);
  } finally {
    await client.close();
  }
}

main();
