import type { ArbitrageOpportunity, Exchange, ArbitrageBot, ArbitrageStats } from "./types"

export const mockExchanges: Exchange[] = [
  {
    id: "binance",
    name: "Binance",
    logo: "/placeholder.svg?height=32&width=32",
    status: "connected",
    apiKeyConfigured: true,
  },
  {
    id: "coinbase",
    name: "Coinbase",
    logo: "/placeholder.svg?height=32&width=32",
    status: "connected",
    apiKeyConfigured: true,
  },
  {
    id: "kraken",
    name: "Kraken",
    logo: "/placeholder.svg?height=32&width=32",
    status: "disconnected",
    apiKeyConfigured: false,
  },
  {
    id: "kucoin",
    name: "KuCoin",
    logo: "/placeholder.svg?height=32&width=32",
    status: "error",
    apiKeyConfigured: true,
  },
  {
    id: "ftx",
    name: "FTX",
    logo: "/placeholder.svg?height=32&width=32",
    status: "disconnected",
    apiKeyConfigured: false,
  },
]

export const mockArbitrageBots: ArbitrageBot[] = [
  {
    id: "bot1",
    name: "BTC/ETH Arbitrage",
    status: "active",
    exchanges: ["binance", "coinbase"],
    pairs: ["BTC/USDT", "ETH/USDT"],
    minSpread: 0.5,
    maxVolume: 10000,
    profitThreshold: 0.2,
    createdAt: new Date("2023-01-15"),
    lastActive: new Date(),
    totalTrades: 156,
    successRate: 92,
    totalProfit: 1245.67,
  },
  {
    id: "bot2",
    name: "Stablecoin Arbitrage",
    status: "paused",
    exchanges: ["binance", "kucoin"],
    pairs: ["USDC/USDT", "DAI/USDT"],
    minSpread: 0.1,
    maxVolume: 50000,
    profitThreshold: 0.05,
    createdAt: new Date("2023-03-22"),
    lastActive: new Date("2023-05-10"),
    totalTrades: 312,
    successRate: 97,
    totalProfit: 876.32,
  },
  {
    id: "bot3",
    name: "Altcoin Hunter",
    status: "stopped",
    exchanges: ["binance", "coinbase", "kucoin"],
    pairs: ["SOL/USDT", "ADA/USDT", "DOT/USDT"],
    minSpread: 1.0,
    maxVolume: 5000,
    profitThreshold: 0.5,
    createdAt: new Date("2023-02-10"),
    lastActive: new Date("2023-04-15"),
    totalTrades: 78,
    successRate: 85,
    totalProfit: 1567.89,
  },
  {
    id: "bot4",
    name: "BNB-ETH Arbitrage",
    status: "active",
    exchanges: ["binance", "kucoin"],
    pairs: ["BNB/USDT", "ETH/USDT"],
    minSpread: 0.4,
    maxVolume: 8000,
    profitThreshold: 0.25,
    createdAt: new Date("2023-04-05"),
    lastActive: new Date(),
    totalTrades: 98,
    successRate: 89,
    totalProfit: 932.45,
    description: "Specialized bot for arbitrage between BNB and ETH across multiple exchanges",
    settings: {
      executionSpeed: "high",
      slippageTolerance: 0.2,
      gasPrice: "medium",
      maxConcurrentTrades: 3,
      autoRebalance: true,
      rebalanceThreshold: 10,
    },
    performance: {
      daily: 12.34,
      weekly: 87.65,
      monthly: 342.18,
      allTime: 932.45,
      winRate: 89,
      avgProfitPerTrade: 9.51,
      largestProfit: 45.32,
      avgExecutionTime: 1.2,
    },
    recentTrades: [
      {
        id: "trade1",
        timestamp: new Date(Date.now() - 1000 * 60 * 30),
        buyExchange: "Binance",
        sellExchange: "KuCoin",
        pair: "BNB/USDT",
        volume: 2.5,
        spread: 0.52,
        profit: 12.45,
        status: "completed",
        executionTime: 0.9,
      },
      {
        id: "trade2",
        timestamp: new Date(Date.now() - 1000 * 60 * 120),
        buyExchange: "KuCoin",
        sellExchange: "Binance",
        pair: "ETH/USDT",
        volume: 1.2,
        spread: 0.48,
        profit: 8.76,
        status: "completed",
        executionTime: 1.1,
      },
      {
        id: "trade3",
        timestamp: new Date(Date.now() - 1000 * 60 * 240),
        buyExchange: "Binance",
        sellExchange: "KuCoin",
        pair: "BNB/USDT",
        volume: 3.0,
        spread: 0.38,
        profit: 10.89,
        status: "completed",
        executionTime: 1.3,
      },
    ],
    alerts: [
      {
        id: "alert1",
        type: "info",
        message: "Rebalancing completed successfully",
        timestamp: new Date(Date.now() - 1000 * 60 * 180),
      },
      {
        id: "alert2",
        type: "warning",
        message: "Slippage higher than expected on KuCoin",
        timestamp: new Date(Date.now() - 1000 * 60 * 360),
      },
    ],
  },
]

export const mockOpportunities: ArbitrageOpportunity[] = [
  {
    id: "opp1",
    pair: "BTC/USDT",
    buyExchange: "Coinbase",
    sellExchange: "Binance",
    spread: 0.72,
    volume: 5000,
    profit: 36.0,
    status: "active",
    timestamp: new Date(),
  },
  {
    id: "opp2",
    pair: "ETH/USDT",
    buyExchange: "Binance",
    sellExchange: "KuCoin",
    spread: 0.45,
    volume: 3000,
    profit: 13.5,
    status: "active",
    timestamp: new Date(),
  },
  {
    id: "opp3",
    pair: "SOL/USDT",
    buyExchange: "Binance",
    sellExchange: "Coinbase",
    spread: 1.2,
    volume: 2000,
    profit: 24.0,
    status: "completed",
    timestamp: new Date(Date.now() - 1000 * 60 * 5),
    executionTime: 1.2,
  },
  {
    id: "opp4",
    pair: "USDC/USDT",
    buyExchange: "KuCoin",
    sellExchange: "Binance",
    spread: 0.15,
    volume: 10000,
    profit: 15.0,
    status: "completed",
    timestamp: new Date(Date.now() - 1000 * 60 * 15),
    executionTime: 0.8,
  },
  {
    id: "opp5",
    pair: "ADA/USDT",
    buyExchange: "Coinbase",
    sellExchange: "KuCoin",
    spread: 0.85,
    volume: 1500,
    profit: 12.75,
    status: "failed",
    timestamp: new Date(Date.now() - 1000 * 60 * 30),
  },
  {
    id: "opp6",
    pair: "BNB/USDT",
    buyExchange: "Binance",
    sellExchange: "KuCoin",
    spread: 0.62,
    volume: 4000,
    profit: 24.8,
    status: "active",
    timestamp: new Date(),
  },
  {
    id: "opp7",
    pair: "ETH/USDT",
    buyExchange: "KuCoin",
    sellExchange: "Binance",
    spread: 0.51,
    volume: 3500,
    profit: 17.85,
    status: "active",
    timestamp: new Date(),
  },
  {
    id: "opp8",
    pair: "BNB/USDT",
    buyExchange: "KuCoin",
    sellExchange: "Binance",
    spread: 0.48,
    volume: 2800,
    profit: 13.44,
    status: "completed",
    timestamp: new Date(Date.now() - 1000 * 60 * 45),
    executionTime: 1.0,
  },
]

export const mockStats: ArbitrageStats = {
  totalProfit: 3689.88,
  totalTrades: 546,
  successRate: 94,
  avgExecutionTime: 1.1,
  bestPair: "BTC/USDT",
  bestExchangePair: "Binance → Coinbase",
  largestSpread: 1.8,
}

// BNB-ETH specific historical data
export const bnbEthHistoricalData = {
  dailyProfits: [
    { date: "2023-05-01", profit: 8.45 },
    { date: "2023-05-02", profit: 10.23 },
    { date: "2023-05-03", profit: 7.89 },
    { date: "2023-05-04", profit: 12.34 },
    { date: "2023-05-05", profit: 9.56 },
    { date: "2023-05-06", profit: 11.78 },
    { date: "2023-05-07", profit: 14.23 },
  ],
  spreadHistory: [
    { timestamp: "2023-05-07T09:00:00", spread: 0.42 },
    { timestamp: "2023-05-07T10:00:00", spread: 0.38 },
    { timestamp: "2023-05-07T11:00:00", spread: 0.45 },
    { timestamp: "2023-05-07T12:00:00", spread: 0.51 },
    { timestamp: "2023-05-07T13:00:00", spread: 0.48 },
    { timestamp: "2023-05-07T14:00:00", spread: 0.52 },
    { timestamp: "2023-05-07T15:00:00", spread: 0.49 },
  ],
  volumeHistory: [
    { timestamp: "2023-05-07T09:00:00", volume: 2500 },
    { timestamp: "2023-05-07T10:00:00", volume: 3200 },
    { timestamp: "2023-05-07T11:00:00", volume: 2800 },
    { timestamp: "2023-05-07T12:00:00", volume: 3500 },
    { timestamp: "2023-05-07T13:00:00", volume: 4000 },
    { timestamp: "2023-05-07T14:00:00", volume: 3800 },
    { timestamp: "2023-05-07T15:00:00", volume: 4200 },
  ],
}
