import type { StrategyData, Position, Trade, PerformanceData, WatchSignal } from "./types"

// Mock performance data for charts
const mockPerformanceData: PerformanceData[] = [
  { date: "2024-01-01", balance: 1000, profit: 0, trades: 0, winRate: 0 },
  { date: "2024-01-03", balance: 1025, profit: 25, trades: 2, winRate: 100 },
  { date: "2024-01-05", balance: 1050, profit: 50, trades: 4, winRate: 75 },
  { date: "2024-01-07", balance: 1035, profit: 35, trades: 5, winRate: 60 },
  { date: "2024-01-09", balance: 1080, profit: 80, trades: 7, winRate: 71.4 },
  { date: "2024-01-11", balance: 1120, profit: 120, trades: 9, winRate: 77.8 },
  { date: "2024-01-13", balance: 1095, profit: 95, trades: 11, winRate: 63.6 },
  { date: "2024-01-15", balance: 1245.80, profit: 245.80, trades: 15, winRate: 66.7 },
]

// Mock positions for strategy 1
const mockPositions1: Position[] = [
  {
    id: "pos-1",
    marketId: "mkt-1",
    marketTitle: "Will Trump win the 2024 US Presidential Election?",
    marketSlug: "trump-2024-election",
    outcome: "YES",
    shares: 150,
    averagePrice: 0.62,
    currentPrice: 0.71,
    unrealizedPnL: 13.5,
    realizedPnL: 0,
    category: "Politics",
    status: "open",
    openedAt: "2024-01-10T14:30:00Z",
  },
  {
    id: "pos-2",
    marketId: "mkt-2",
    marketTitle: "Will Bitcoin reach $100k by end of 2024?",
    marketSlug: "bitcoin-100k-2024",
    outcome: "NO",
    shares: 200,
    averagePrice: 0.35,
    currentPrice: 0.42,
    unrealizedPnL: -14.0,
    realizedPnL: 0,
    category: "Crypto",
    status: "open",
    openedAt: "2024-01-12T10:15:00Z",
  },
  {
    id: "pos-3",
    marketId: "mkt-3",
    marketTitle: "Will the Fed cut rates in March 2024?",
    marketSlug: "fed-rates-march-2024",
    outcome: "YES",
    shares: 100,
    averagePrice: 0.55,
    currentPrice: 0.48,
    unrealizedPnL: -7.0,
    realizedPnL: 0,
    category: "Finance",
    status: "open",
    openedAt: "2024-01-15T09:00:00Z",
  },
]

// Mock trades for strategy 1
const mockTrades1: Trade[] = [
  {
    id: "trade-1",
    timestamp: "2024-01-15T09:00:00Z",
    marketTitle: "Will the Fed cut rates in March 2024?",
    type: "buy",
    outcome: "YES",
    shares: 100,
    price: 0.55,
    amount: 55.0,
    status: "completed",
    fees: 0.55,
  },
  {
    id: "trade-2",
    timestamp: "2024-01-12T10:15:00Z",
    marketTitle: "Will Bitcoin reach $100k by end of 2024?",
    type: "buy",
    outcome: "NO",
    shares: 200,
    price: 0.35,
    amount: 70.0,
    status: "completed",
    fees: 0.70,
  },
  {
    id: "trade-3",
    timestamp: "2024-01-10T14:30:00Z",
    marketTitle: "Will Trump win the 2024 US Presidential Election?",
    type: "buy",
    outcome: "YES",
    shares: 150,
    price: 0.62,
    amount: 93.0,
    status: "completed",
    fees: 0.93,
  },
]

// Mock watch signals for strategy 1
const mockWatchSignals1: WatchSignal[] = [
  {
    id: "watch-1",
    marketId: "mkt-watch-1",
    marketTitle: "Will Apple announce a new AR headset in 2024?",
    category: "Tech",
    currentPrice: 0.68,
    sii: 78,
    volume24h: 125000,
    momentum: 12.5,
    flaggedAt: "2024-01-16T08:30:00Z",
    reason: "High SII signal (78) combined with strong positive momentum and increasing 24h volume. Market shows technical setup matching entry criteria.",
    confidence: "high",
    suggestedOutcome: "YES",
  },
  {
    id: "watch-2",
    marketId: "mkt-watch-2",
    marketTitle: "Will the S&P 500 hit 5000 before March 2024?",
    category: "Finance",
    currentPrice: 0.45,
    sii: 82,
    volume24h: 340000,
    momentum: 8.3,
    flaggedAt: "2024-01-16T06:15:00Z",
    reason: "Extremely high SII (82) with substantial trading volume. Momentum indicators showing sustained upward pressure.",
    confidence: "high",
    suggestedOutcome: "YES",
  },
  {
    id: "watch-3",
    marketId: "mkt-watch-3",
    marketTitle: "Will there be a government shutdown in February 2024?",
    category: "Politics",
    currentPrice: 0.32,
    sii: 52,
    volume24h: 85000,
    momentum: -3.2,
    flaggedAt: "2024-01-15T20:45:00Z",
    reason: "Moderate SII signal with recent price movement creating potential entry opportunity. Volume trending higher.",
    confidence: "medium",
    suggestedOutcome: "NO",
  },
  {
    id: "watch-4",
    marketId: "mkt-watch-4",
    marketTitle: "Will Ethereum surpass $3000 in January 2024?",
    category: "Crypto",
    currentPrice: 0.58,
    sii: 45,
    volume24h: 95000,
    momentum: 5.7,
    flaggedAt: "2024-01-15T18:00:00Z",
    reason: "Price momentum building with decent volume. SII approaching threshold but not quite at target levels yet.",
    confidence: "low",
    suggestedOutcome: "YES",
  },
]

// Mock Strategy 1: High SII Politics Strategy
export const mockStrategy1: StrategyData = {
  id: "strategy-1",
  name: "High SII Politics Strategy",
  description: "Automated strategy targeting high SII political markets with momentum indicators",
  status: "active",
  createdAt: "2024-01-01T00:00:00Z",
  balance: 1245.80,
  initialBalance: 1000.0,
  performance: {
    daily: 2.3,
    weekly: 8.5,
    monthly: 18.2,
    total: 24.58,
  },
  performanceData: mockPerformanceData,
  positions: mockPositions1,
  recentTrades: mockTrades1,
  watchSignals: mockWatchSignals1,
  statistics: {
    totalTrades: 15,
    winningTrades: 10,
    losingTrades: 5,
    winRate: 66.7,
    averageWin: 18.5,
    averageLoss: -12.3,
    profitFactor: 1.5,
    sharpeRatio: 1.8,
    maxDrawdown: -8.5,
    currentDrawdown: -2.1,
    activePositions: 3,
    closedPositions: 12,
  },
  settings: {
    maxPositionSize: 200,
    maxPositions: 5,
    stopLoss: -15,
    takeProfit: 25,
    categories: ["Politics"],
    minVolume: 50000,
    minLiquidity: 10000,
    siiThreshold: 0.7,
    momentumThreshold: 0.6,
    riskLevel: "medium",
  },
  aiInsights: [
    {
      id: "insight-1",
      timestamp: "2024-01-15T12:00:00Z",
      message: "High momentum detected in political markets - consider increasing position sizes",
      type: "opportunity",
      impact: "positive",
      actionable: true,
    },
    {
      id: "insight-2",
      timestamp: "2024-01-14T18:30:00Z",
      message: "Bitcoin market showing divergence from typical patterns - monitor closely",
      type: "warning",
      impact: "neutral",
      actionable: true,
    },
  ],
  nodeGraph: {
    nodes: [
      {
        id: "data-source-1",
        type: "DATA_SOURCE" as const,
        config: {
          source: "MARKETS" as const,
          filters: [],
        },
      },
      {
        id: "filter-1",
        type: "FILTER" as const,
        config: {
          conditions: [],
          logic: "AND" as const,
        },
      },
    ],
    edges: [
      {
        from: "data-source-1",
        to: "filter-1",
      },
    ],
  },
  marketConditions: {
    overall: "Bullish",
    volume: "High",
    volatility: "Medium",
    sentiment: "Positive",
    topCategories: ["Politics", "Crypto", "Finance"],
  },
}

// Mock Strategy 2: Crypto Momentum Strategy
export const mockStrategy2: StrategyData = {
  id: "strategy-2",
  name: "Crypto Momentum Strategy",
  description: "Focus on high-momentum cryptocurrency prediction markets",
  status: "active",
  createdAt: "2024-01-05T00:00:00Z",
  balance: 876.50,
  initialBalance: 800.0,
  performance: {
    daily: 1.2,
    weekly: 4.8,
    monthly: 7.5,
    total: 9.56,
  },
  performanceData: mockPerformanceData,
  positions: [],
  recentTrades: [],
  watchSignals: [],
  statistics: {
    totalTrades: 8,
    winningTrades: 5,
    losingTrades: 3,
    winRate: 62.5,
    averageWin: 15.2,
    averageLoss: -10.5,
    profitFactor: 1.45,
    sharpeRatio: 1.3,
    maxDrawdown: -5.2,
    currentDrawdown: 0,
    activePositions: 0,
    closedPositions: 8,
  },
  settings: {
    maxPositionSize: 150,
    maxPositions: 4,
    stopLoss: -12,
    takeProfit: 20,
    categories: ["Crypto"],
    minVolume: 30000,
    minLiquidity: 8000,
    siiThreshold: 0.65,
    momentumThreshold: 0.7,
    riskLevel: "high",
  },
  aiInsights: [],
  nodeGraph: {
    nodes: [
      {
        id: "data-source-2",
        type: "DATA_SOURCE" as const,
        config: {
          source: "MARKETS" as const,
          filters: [],
        },
      },
      {
        id: "filter-2",
        type: "FILTER" as const,
        config: {
          conditions: [],
          logic: "AND" as const,
        },
      },
    ],
    edges: [
      {
        from: "data-source-2",
        to: "filter-2",
      },
    ],
  },
  marketConditions: {
    overall: "Neutral",
    volume: "Medium",
    volatility: "High",
    sentiment: "Mixed",
    topCategories: ["Crypto", "Tech"],
  },
}

// Mock Strategy 3: Conservative Multi-Category
export const mockStrategy3: StrategyData = {
  id: "strategy-3",
  name: "Conservative Multi-Category",
  description: "Low-risk diversified strategy across multiple market categories",
  status: "paused",
  createdAt: "2023-12-15T00:00:00Z",
  balance: 1523.20,
  initialBalance: 1500.0,
  performance: {
    daily: 0.1,
    weekly: 0.8,
    monthly: 1.2,
    total: 1.55,
  },
  performanceData: mockPerformanceData,
  positions: [],
  recentTrades: [],
  watchSignals: [],
  statistics: {
    totalTrades: 22,
    winningTrades: 16,
    losingTrades: 6,
    winRate: 72.7,
    averageWin: 8.5,
    averageLoss: -5.2,
    profitFactor: 2.6,
    sharpeRatio: 2.1,
    maxDrawdown: -3.1,
    currentDrawdown: 0,
    activePositions: 0,
    closedPositions: 22,
  },
  settings: {
    maxPositionSize: 100,
    maxPositions: 8,
    stopLoss: -8,
    takeProfit: 12,
    categories: ["Politics", "Sports", "Finance", "Pop Culture"],
    minVolume: 100000,
    minLiquidity: 20000,
    siiThreshold: 0.75,
    momentumThreshold: 0.55,
    riskLevel: "low",
  },
  aiInsights: [],
  nodeGraph: {
    nodes: [
      {
        id: "data-source-3",
        type: "DATA_SOURCE" as const,
        config: {
          source: "MARKETS" as const,
          filters: [],
        },
      },
      {
        id: "filter-3",
        type: "FILTER" as const,
        config: {
          conditions: [],
          logic: "AND" as const,
        },
      },
    ],
    edges: [
      {
        from: "data-source-3",
        to: "filter-3",
      },
    ],
  },
  marketConditions: {
    overall: "Stable",
    volume: "High",
    volatility: "Low",
    sentiment: "Positive",
    topCategories: ["Politics", "Finance", "Sports"],
  },
}

// Mock Default Template Strategy
export const mockDefaultStrategy: StrategyData = {
  id: "default-template",
  name: "Default Template",
  description: "The standard CASCADIAN intelligence trading strategy for prediction markets",
  status: "active",
  createdAt: "2024-01-01T00:00:00Z",
  balance: 1245.80,
  initialBalance: 1000.0,
  performance: {
    daily: 2.3,
    weekly: 8.5,
    monthly: 18.2,
    total: 24.58,
  },
  performanceData: mockPerformanceData,
  positions: mockPositions1,
  recentTrades: mockTrades1,
  watchSignals: mockWatchSignals1,
  statistics: {
    totalTrades: 15,
    winningTrades: 10,
    losingTrades: 5,
    winRate: 66.7,
    averageWin: 18.5,
    averageLoss: -12.3,
    profitFactor: 1.5,
    sharpeRatio: 1.8,
    maxDrawdown: -8.5,
    currentDrawdown: -2.1,
    activePositions: 3,
    closedPositions: 12,
  },
  settings: {
    maxPositionSize: 200,
    maxPositions: 5,
    stopLoss: -15,
    takeProfit: 25,
    categories: ["Politics", "Crypto", "Finance"],
    minVolume: 50000,
    minLiquidity: 10000,
    siiThreshold: 0.7,
    momentumThreshold: 0.6,
    riskLevel: "medium",
  },
  aiInsights: [
    {
      id: "insight-1",
      timestamp: "2024-01-15T12:00:00Z",
      message: "High momentum detected in political markets - consider increasing position sizes",
      type: "opportunity",
      impact: "positive",
      actionable: true,
    },
    {
      id: "insight-2",
      timestamp: "2024-01-14T18:30:00Z",
      message: "Bitcoin market showing divergence from typical patterns - monitor closely",
      type: "warning",
      impact: "neutral",
      actionable: true,
    },
  ],
  nodeGraph: {
    nodes: [
      {
        id: "data-source-default",
        type: "DATA_SOURCE" as const,
        config: {
          source: "MARKETS" as const,
          filters: [],
        },
      },
      {
        id: "filter-default",
        type: "FILTER" as const,
        config: {
          conditions: [],
          logic: "AND" as const,
        },
      },
    ],
    edges: [
      {
        from: "data-source-default",
        to: "filter-default",
      },
    ],
  },
  marketConditions: {
    overall: "Bullish",
    volume: "High",
    volatility: "Medium",
    sentiment: "Positive",
    topCategories: ["Politics", "Crypto", "Finance"],
  },
}

export const mockStrategies: StrategyData[] = [
  mockDefaultStrategy,
  mockStrategy1,
  mockStrategy2,
  mockStrategy3,
]
