import type { SignalProvider, Signal, PerformanceStats } from "./types"

export const mockSignalProviders: SignalProvider[] = [
  {
    id: "provider-1",
    name: "CryptoSignals Pro",
    avatar: "/placeholder.svg?height=40&width=40",
    description: "Professional crypto signals with high accuracy",
    accuracy: 87,
    signals: 1243,
    subscribers: 5600,
    price: "Free",
    status: "active",
    favorite: true,
  },
  {
    id: "provider-2",
    name: "WhaleAlert Signals",
    avatar: "/placeholder.svg?height=40&width=40",
    description: "Signals based on whale movements and market analysis",
    accuracy: 82,
    signals: 876,
    subscribers: 3200,
    price: "$29.99/mo",
    status: "active",
    favorite: true,
  },
  {
    id: "provider-3",
    name: "AI Crypto Insights",
    avatar: "/placeholder.svg?height=40&width=40",
    description: "AI-powered trading signals with technical analysis",
    accuracy: 79,
    signals: 2156,
    subscribers: 4100,
    price: "$49.99/mo",
    status: "inactive",
    favorite: false,
  },
  {
    id: "provider-4",
    name: "DeFi Pulse",
    avatar: "/placeholder.svg?height=40&width=40",
    description: "DeFi-focused signals and yield farming opportunities",
    accuracy: 84,
    signals: 932,
    subscribers: 2800,
    price: "$19.99/mo",
    status: "active",
    favorite: false,
  },
  {
    id: "provider-5",
    name: "Crypto Insider",
    avatar: "/placeholder.svg?height=40&width=40",
    description: "Insider trading signals and market analysis",
    accuracy: 76,
    signals: 1567,
    subscribers: 3900,
    price: "$39.99/mo",
    status: "inactive",
    favorite: false,
  },
]

export const mockRecentSignals: Signal[] = [
  {
    id: "signal-1",
    provider: "CryptoSignals Pro",
    providerAvatar: "/placeholder.svg?height=32&width=32",
    asset: "BTC/USDT",
    type: "LONG",
    entryPrice: 68450,
    targetPrice: 72000,
    stopLoss: 66800,
    timestamp: "2023-05-15T08:30:00Z",
    status: "active",
    profit: null,
    confidence: 92,
  },
  {
    id: "signal-2",
    provider: "WhaleAlert Signals",
    providerAvatar: "/placeholder.svg?height=32&width=32",
    asset: "ETH/USDT",
    type: "SHORT",
    entryPrice: 3450,
    targetPrice: 3200,
    stopLoss: 3550,
    timestamp: "2023-05-15T07:15:00Z",
    status: "active",
    profit: null,
    confidence: 87,
  },
  {
    id: "signal-3",
    provider: "AI Crypto Insights",
    providerAvatar: "/placeholder.svg?height=32&width=32",
    asset: "SOL/USDT",
    type: "LONG",
    entryPrice: 142.5,
    targetPrice: 155,
    stopLoss: 138,
    timestamp: "2023-05-15T06:45:00Z",
    status: "completed",
    profit: 8.77,
    confidence: 89,
  },
  {
    id: "signal-4",
    provider: "DeFi Pulse",
    providerAvatar: "/placeholder.svg?height=32&width=32",
    asset: "AVAX/USDT",
    type: "LONG",
    entryPrice: 35.2,
    targetPrice: 38.5,
    stopLoss: 33.8,
    timestamp: "2023-05-14T22:10:00Z",
    status: "completed",
    profit: 9.38,
    confidence: 84,
  },
  {
    id: "signal-5",
    provider: "CryptoSignals Pro",
    providerAvatar: "/placeholder.svg?height=32&width=32",
    asset: "BNB/USDT",
    type: "SHORT",
    entryPrice: 610,
    targetPrice: 580,
    stopLoss: 625,
    timestamp: "2023-05-14T18:30:00Z",
    status: "stopped",
    profit: -2.46,
    confidence: 78,
  },
]

export const mockSignalHistory: Signal[] = [
  ...mockRecentSignals,
  {
    id: "signal-6",
    provider: "WhaleAlert Signals",
    providerAvatar: "/placeholder.svg?height=32&width=32",
    asset: "XRP/USDT",
    type: "LONG",
    entryPrice: 0.52,
    targetPrice: 0.58,
    stopLoss: 0.49,
    timestamp: "2023-05-14T14:20:00Z",
    status: "completed",
    profit: 11.54,
    confidence: 91,
  },
  {
    id: "signal-7",
    provider: "AI Crypto Insights",
    providerAvatar: "/placeholder.svg?height=32&width=32",
    asset: "DOT/USDT",
    type: "LONG",
    entryPrice: 6.8,
    targetPrice: 7.5,
    stopLoss: 6.5,
    timestamp: "2023-05-14T10:15:00Z",
    status: "completed",
    profit: 10.29,
    confidence: 86,
  },
  {
    id: "signal-8",
    provider: "CryptoSignals Pro",
    providerAvatar: "/placeholder.svg?height=32&width=32",
    asset: "ADA/USDT",
    type: "SHORT",
    entryPrice: 0.48,
    targetPrice: 0.44,
    stopLoss: 0.5,
    timestamp: "2023-05-14T08:30:00Z",
    status: "stopped",
    profit: -4.17,
    confidence: 75,
  },
  {
    id: "signal-9",
    provider: "DeFi Pulse",
    providerAvatar: "/placeholder.svg?height=32&width=32",
    asset: "LINK/USDT",
    type: "LONG",
    entryPrice: 15.2,
    targetPrice: 16.8,
    stopLoss: 14.5,
    timestamp: "2023-05-13T22:45:00Z",
    status: "completed",
    profit: 10.53,
    confidence: 88,
  },
  {
    id: "signal-10",
    provider: "WhaleAlert Signals",
    providerAvatar: "/placeholder.svg?height=32&width=32",
    asset: "MATIC/USDT",
    type: "LONG",
    entryPrice: 0.86,
    targetPrice: 0.95,
    stopLoss: 0.82,
    timestamp: "2023-05-13T16:10:00Z",
    status: "completed",
    profit: 10.47,
    confidence: 83,
  },
]

export const performanceStats: PerformanceStats = {
  totalSignals: 1243,
  successRate: 78,
  avgProfit: 9.2,
  totalProfit: 12450,
  activeSignals: 12,
  completedSignals: 987,
  stoppedSignals: 244,
}

export const chartData = [
  { date: "Jan", profit: 5.2, signals: 45 },
  { date: "Feb", profit: 8.1, signals: 52 },
  { date: "Mar", profit: 12.3, signals: 48 },
  { date: "Apr", profit: 9.7, signals: 61 },
  { date: "May", profit: 15.2, signals: 58 },
  { date: "Jun", profit: 18.9, signals: 67 },
]

export const weeklyPerformanceData = [
  { week: "Week 1", profit: 2.1, winRate: 65 },
  { week: "Week 2", profit: 5.3, winRate: 72 },
  { week: "Week 3", profit: 8.7, winRate: 68 },
  { week: "Week 4", profit: 12.4, winRate: 78 },
]

export const dailyPerformanceData = [
  { day: "Mon", performance: 2.1 },
  { day: "Tue", performance: 1.8 },
  { day: "Wed", performance: 3.2 },
  { day: "Thu", performance: 2.7 },
  { day: "Fri", performance: 4.1 },
  { day: "Sat", performance: 1.9 },
  { day: "Sun", performance: 3.5 },
]
